In [57]:
import pickle
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_style('whitegrid')

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [58]:
pd.set_option('display.max_columns', 200)
pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.width', 1000)

In [176]:
import pickle
data = pd.read_pickle('dataupdate28042018.pkl')

In [177]:
data.head()

       loan_amnt  funded_amnt  funded_amnt_inv        term  int_rate  installment grade sub_grade                            emp_title emp_length home_ownership  annual_inc verification_status   issue_d             purpose zip_code addr_state    dti  delinq_2yrs earliest_cr_line  inq_last_6mths  mths_since_last_delinq  open_acc  pub_rec  revol_bal revol_util  total_acc initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee  last_pymnt_amnt     next_pymnt_d last_credit_pull_d  collections_12_mths_ex_med application_type  acc_now_delinq  tot_coll_amt  tot_cur_bal  total_rev_hi_lim  DEFAULT
42536    27050.0      27050.0          27050.0   36 months     10.99       885.46     B        B2  team leadern customer ops & systems  10+ years            OWN     55000.0            Verified  Dec-2013  debt_consolidation    481xx         MI  22.87          0.0         Oct-1986             0.0                     0.0      14.0      0.0    36638.0      61.2%       27.0                   w   10018.90       10018.90     21251.04         21251.04         17031.10        4219.94                 0.0         0.0                      0.0           885.46         Feb-2016           Dec-2015                         0.0       INDIVIDUAL             0.0           0.0     114834.0           59900.0        0
42537     9750.0       9750.0           9750.0   36 months     13.98       333.14     C        C1                    medical assistant     1 year           RENT     26000.0        Not Verified  Dec-2013  debt_consolidation    927xx         CA  25.12          0.0         Jan-2007             0.0                     0.0      12.0      0.0     7967.0      52.8%       28.0                   f    3710.96        3710.96      7994.83          7994.83          6039.04        1955.79                 0.0         0.0                      0.0           333.14         Feb-2016           Jan-2016                         0.0       INDIVIDUAL             0.0           0.0      14123.0           15100.0        0
42538    12000.0      12000.0          12000.0   36 months      6.62       368.45     A        A2         manager information delivery  10+ years       MORTGAGE    105000.0        Not Verified  Dec-2013  debt_consolidation    060xx         CT  14.05          0.0         Mar-1994             1.0                    43.0      12.0      0.0    13168.0      21.6%       22.0                   w    4266.62        4266.62      8842.80          8842.80          7733.38        1109.42                 0.0         0.0                      0.0           368.45         Feb-2016           Jan-2016                         0.0       INDIVIDUAL             0.0           0.0     267646.0           61100.0        0
42539    12000.0      12000.0          12000.0   36 months     13.53       407.40     B        B5                      on road manager  10+ years           RENT     40000.0     Source Verified  Dec-2013  debt_consolidation    871xx         NM  16.94          0.0         Oct-1998             0.0                    53.0       7.0      2.0     5572.0      68.8%       32.0                   w       0.00           0.00     13359.77         13359.77         11999.99        1359.78                 0.0         0.0                      0.0           119.17  isthisrelevant?           Jan-2016                         0.0       INDIVIDUAL             0.0       15386.0      13605.0            8100.0        0
42540    15000.0      15000.0          15000.0   36 months      8.90       476.30     A        A5        aircraft maintenance engineer    2 years       MORTGAGE     63000.0        Not Verified  Dec-2013  debt_consolidation    334xx         FL  16.51          0.0         Mar-1998             0.0                    34.0       8.0      0.0    11431.0      74.2%       29.0                   w    5449.27        5449.27     11431.20         11431.20          9550.73        1880.47                 0.0         0.0                      0.0           476.30         Feb-2016           Jan-2016                         0.0       INDIVIDUAL             0.0        1514.0     272492.0           15400.0        0

In [178]:
data['DEFAULT'].value_counts()

0    766486
1     50190
Name: DEFAULT, dtype: int64

In [179]:
# data.dtypes

In [180]:
# dropping the emp_title and columns
data = data.drop(['emp_title'], axis=1)
data = data.drop(['zip_code'], axis=1)

In [181]:
# this was added in last iteration on 160502018 to remove unrequired date columns
data = data.drop(['last_credit_pull_d','next_pymnt_d','earliest_cr_line'], axis=1)

In [182]:
data['revol_util'] = data['revol_util'].str.replace('%','')
data['revol_util'] = data['revol_util'].astype(float)

In [183]:
data.head()

       loan_amnt  funded_amnt  funded_amnt_inv        term  int_rate  installment grade sub_grade emp_length home_ownership  annual_inc verification_status   issue_d             purpose addr_state    dti  delinq_2yrs  inq_last_6mths  mths_since_last_delinq  open_acc  pub_rec  revol_bal  revol_util  total_acc initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee  last_pymnt_amnt  collections_12_mths_ex_med application_type  acc_now_delinq  tot_coll_amt  tot_cur_bal  total_rev_hi_lim  DEFAULT
42536    27050.0      27050.0          27050.0   36 months     10.99       885.46     B        B2  10+ years            OWN     55000.0            Verified  Dec-2013  debt_consolidation         MI  22.87          0.0             0.0                     0.0      14.0      0.0    36638.0        61.2       27.0                   w   10018.90       10018.90     21251.04         21251.04         17031.10        4219.94                 0.0         0.0                      0.0           885.46                         0.0       INDIVIDUAL             0.0           0.0     114834.0           59900.0        0
42537     9750.0       9750.0           9750.0   36 months     13.98       333.14     C        C1     1 year           RENT     26000.0        Not Verified  Dec-2013  debt_consolidation         CA  25.12          0.0             0.0                     0.0      12.0      0.0     7967.0        52.8       28.0                   f    3710.96        3710.96      7994.83          7994.83          6039.04        1955.79                 0.0         0.0                      0.0           333.14                         0.0       INDIVIDUAL             0.0           0.0      14123.0           15100.0        0
42538    12000.0      12000.0          12000.0   36 months      6.62       368.45     A        A2  10+ years       MORTGAGE    105000.0        Not Verified  Dec-2013  debt_consolidation         CT  14.05          0.0             1.0                    43.0      12.0      0.0    13168.0        21.6       22.0                   w    4266.62        4266.62      8842.80          8842.80          7733.38        1109.42                 0.0         0.0                      0.0           368.45                         0.0       INDIVIDUAL             0.0           0.0     267646.0           61100.0        0
42539    12000.0      12000.0          12000.0   36 months     13.53       407.40     B        B5  10+ years           RENT     40000.0     Source Verified  Dec-2013  debt_consolidation         NM  16.94          0.0             0.0                    53.0       7.0      2.0     5572.0        68.8       32.0                   w       0.00           0.00     13359.77         13359.77         11999.99        1359.78                 0.0         0.0                      0.0           119.17                         0.0       INDIVIDUAL             0.0       15386.0      13605.0            8100.0        0
42540    15000.0      15000.0          15000.0   36 months      8.90       476.30     A        A5    2 years       MORTGAGE     63000.0        Not Verified  Dec-2013  debt_consolidation         FL  16.51          0.0             0.0                    34.0       8.0      0.0    11431.0        74.2       29.0                   w    5449.27        5449.27     11431.20         11431.20          9550.73        1880.47                 0.0         0.0                      0.0           476.30                         0.0       INDIVIDUAL             0.0        1514.0     272492.0           15400.0        0

In [184]:
data = data.drop(['collection_recovery_fee', 'recoveries','total_rec_late_fee'], axis=1)

In [119]:
# drops done in run on 230502018
# data = data.drop(['addr_state','purpose'], axis=1)

In [156]:
# additional drops done in run on 230502018
# data = data.drop(['emp_length','delinq_2yrs','funded_amnt_inv','funded_amnt','loan_amnt','tot_coll_amt',\
#                   'application_type'], axis=1)

In [166]:
# additional drops done in run on 230502018
# data = data.drop(['open_acc','pub_rec','total_acc','mths_since_last_delinq','collections_12_mths_ex_med','acc_now_delinq',\
#                  'dti'], axis=1)

In [71]:
#data['outprinciple'] = data['out_prncp_inv']+ data['out_prncp']
#data['totalpayment'] = data['total_pymnt_inv']+ data['total_pymnt']
#data['totalreceived'] = data['total_rec_prncp']+data['total_rec_int']

In [72]:
# additional drops done in run on 250502018
#data = data.drop(['out_prncp_inv','out_prncp','total_pymnt','total_pymnt_inv'], axis=1)
#data = data.drop(['total_rec_int','total_rec_prncp','total_pymnt','total_pymnt_inv'], axis=1)

In [185]:
catdatacol = [x for x in data.columns if data[x].dtype == object]
numdatacol = [x for x in data.columns if data[x].dtype != object]
# catdatacol

In [186]:
data[catdatacol].head()

             term grade sub_grade emp_length home_ownership verification_status   issue_d             purpose addr_state initial_list_status application_type
42536   36 months     B        B2  10+ years            OWN            Verified  Dec-2013  debt_consolidation         MI                   w       INDIVIDUAL
42537   36 months     C        C1     1 year           RENT        Not Verified  Dec-2013  debt_consolidation         CA                   f       INDIVIDUAL
42538   36 months     A        A2  10+ years       MORTGAGE        Not Verified  Dec-2013  debt_consolidation         CT                   w       INDIVIDUAL
42539   36 months     B        B5  10+ years           RENT     Source Verified  Dec-2013  debt_consolidation         NM                   w       INDIVIDUAL
42540   36 months     A        A5    2 years       MORTGAGE        Not Verified  Dec-2013  debt_consolidation         FL                   w       INDIVIDUAL

In [187]:
temp_dummy = pd.get_dummies(data[catdatacol], prefix=catdatacol, columns=catdatacol ,drop_first=True)

In [188]:
temp_dummy.head()

,term_ 60 months,grade_B,grade_C,grade_D,grade_E,grade_F,grade_G,sub_grade_A2,sub_grade_A3,sub_grade_A4,sub_grade_A5,sub_grade_B1,sub_grade_B2,sub_grade_B3,sub_grade_B4,sub_grade_B5,sub_grade_C1,sub_grade_C2,sub_grade_C3,sub_grade_C4,sub_grade_C5,sub_grade_D1,sub_grade_D2,sub_grade_D3,sub_grade_D4,sub_grade_D5,sub_grade_E1,sub_grade_E2,sub_grade_E3,sub_grade_E4,sub_grade_E5,sub_grade_F1,sub_grade_F2,sub_grade_F3,sub_grade_F4,sub_grade_F5,sub_grade_G1,sub_grade_G2,sub_grade_G3,sub_grade_G4,sub_grade_G5,emp_length_10+ years,emp_length_2 years,emp_length_3 years,emp_length_4 years,emp_length_5 years,emp_length_6 years,emp_length_7 years,emp_length_8 years,emp_length_9 years,emp_length_< 1 year,emp_length_n/a,home_ownership_MORTGAGE,home_ownership_NONE,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT,verification_status_Source Verified,verification_status_Verified,issue_d_Apr-2014,issue_d_Apr-2015,issue_d_Aug-2012,issue_d_Aug-2013,issue_d_Aug-2014,issue_d_Aug-2015,issue_d_Dec-2012,issue_d_Dec-2013,issue_d_Dec-2014,issue_d_Dec-2015,issue_d_Feb-2013,issue_d_Feb-2014,issue_d_Feb-2015,issue_d_Jan-2013,issue_d_Jan-2014,issue_d_Jan-2015,issue_d_Jul-2013,issue_d_Jul-2014,issue_d_Jul-2015,issue_d_Jun-2013,issue_d_Jun-2014,issue_d_Jun-2015,issue_d_Mar-2013,issue_d_Mar-2014,issue_d_Mar-2015,issue_d_May-2013,issue_d_May-2014,issue_d_May-2015,issue_d_Nov-2012,issue_d_Nov-2013,issue_d_Nov-2014,issue_d_Nov-2015,issue_d_Oct-2012,issue_d_Oct-2013,issue_d_Oct-2014,issue_d_Oct-2015,issue_d_Sep-2012,issue_d_Sep-2013,issue_d_Sep-2014,issue_d_Sep-2015,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,addr_state_AL,addr_state_AR,addr_state_AZ,addr_state_CA,addr_state_CO,addr_state_CT,addr_state_DC,addr_state_DE,addr_state_FL,addr_state_GA,addr_state_HI,addr_state_IA,addr_state_ID,addr_state_IL,addr_state_IN,addr_state_KS,addr_state_KY,addr_state_LA,addr_state_MA,addr_state_MD,addr_state_ME,addr_state_MI,addr_state_MN,addr_state_MO,addr_state_MS,addr_state_MT,addr_state_NC,addr_state_ND,addr_state_NE,addr_state_NH,addr_state_NJ,addr_state_NM,addr_state_NV,addr_state_NY,addr_state_OH,addr_state_OK,addr_state_OR,addr_state_PA,addr_state_RI,addr_state_SC,addr_state_SD,addr_state_TN,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY,initial_list_status_w,application_type_JOINT
42536,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
42537,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42538,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
42539,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
42540,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [189]:
# temp_dummy.drop(temp_dummy.iloc[:,0:10],axis=1,inplace=True)
data2 = pd.concat([data[numdatacol],temp_dummy],axis=1)

In [190]:
data2.head()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,last_pymnt_amnt,collections_12_mths_ex_med,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,DEFAULT,term_ 60 months,grade_B,grade_C,grade_D,grade_E,grade_F,grade_G,sub_grade_A2,sub_grade_A3,sub_grade_A4,sub_grade_A5,sub_grade_B1,sub_grade_B2,sub_grade_B3,sub_grade_B4,sub_grade_B5,sub_grade_C1,sub_grade_C2,sub_grade_C3,sub_grade_C4,sub_grade_C5,sub_grade_D1,sub_grade_D2,sub_grade_D3,sub_grade_D4,sub_grade_D5,sub_grade_E1,sub_grade_E2,sub_grade_E3,sub_grade_E4,sub_grade_E5,sub_grade_F1,sub_grade_F2,sub_grade_F3,sub_grade_F4,sub_grade_F5,sub_grade_G1,sub_grade_G2,sub_grade_G3,sub_grade_G4,sub_grade_G5,emp_length_10+ years,emp_length_2 years,emp_length_3 years,emp_length_4 years,emp_length_5 years,emp_length_6 years,emp_length_7 years,emp_length_8 years,emp_length_9 years,emp_length_< 1 year,emp_length_n/a,home_ownership_MORTGAGE,home_ownership_NONE,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT,verification_status_Source Verified,verification_status_Verified,issue_d_Apr-2014,issue_d_Apr-2015,issue_d_Aug-2012,issue_d_Aug-2013,issue_d_Aug-2014,issue_d_Aug-2015,issue_d_Dec-2012,issue_d_Dec-2013,issue_d_Dec-2014,issue_d_Dec-2015,issue_d_Feb-2013,issue_d_Feb-2014,issue_d_Feb-2015,issue_d_Jan-2013,issue_d_Jan-2014,issue_d_Jan-2015,issue_d_Jul-2013,issue_d_Jul-2014,issue_d_Jul-2015,issue_d_Jun-2013,issue_d_Jun-2014,issue_d_Jun-2015,issue_d_Mar-2013,issue_d_Mar-2014,issue_d_Mar-2015,issue_d_May-2013,issue_d_May-2014,issue_d_May-2015,issue_d_Nov-2012,issue_d_Nov-2013,issue_d_Nov-2014,issue_d_Nov-2015,issue_d_Oct-2012,issue_d_Oct-2013,issue_d_Oct-2014,issue_d_Oct-2015,issue_d_Sep-2012,issue_d_Sep-2013,issue_d_Sep-2014,issue_d_Sep-2015,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,addr_state_AL,addr_state_AR,addr_state_AZ,addr_state_CA,addr_state_CO,addr_state_CT,addr_state_DC,addr_state_DE,addr_state_FL,addr_state_GA,addr_state_HI,addr_state_IA,addr_state_ID,addr_state_IL,addr_state_IN,addr_state_KS,addr_state_KY,addr_state_LA,addr_state_MA,addr_state_MD,addr_state_ME,addr_state_MI,addr_state_MN,addr_state_MO,addr_state_MS,addr_state_MT,addr_state_NC,addr_state_ND,addr_state_NE,addr_state_NH,addr_state_NJ,addr_state_NM,addr_state_NV,addr_state_NY,addr_state_OH,addr_state_OK,addr_state_OR,addr_state_PA,addr_state_RI,addr_state_SC,addr_state_SD,addr_state_TN,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY,initial_list_status_w,application_type_JOINT
42536,27050.0,27050.0,27050.0,10.99,885.46,55000.0,22.87,0.0,0.0,0.0,14.0,0.0,36638.0,61.2,27.0,10018.90,10018.90,21251.04,21251.04,17031.10,4219.94,885.46,0.0,0.0,0.0,114834.0,59900.0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
42537,9750.0,9750.0,9750.0,13.98,333.14,26000.0,25.12,0.0,0.0,0.0,12.0,0.0,7967.0,52.8,28.0,3710.96,3710.96,7994.83,7994.83,6039.04,1955.79,333.14,0.0,0.0,0.0,14123.0,15100.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42538,12000.0,12000.0,12000.0,6.62,368.45,105000.0,14.05,0.0,1.0,43.0,12.0,0.0,13168.0,21.6,22.0,4266.62,4266.62,8842.80,8842.80,7733.38,1109.42,368.45,0.0,0.0,0.0,267646.0,61100.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
42539,12000.0,12000.0,12000.0,13.53,407.40,40000.0,16.94,0.0,0.0,53.0,7.0,2.0,5572.0,68.8,32.0,0.00,0.00,13359.77,13359.77,11999.99,1359.78,119.17,0.0,0.0,15386.0,13605.0,8100.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
42540,15000.0,15000.0,15000.0,8.90,476.30,63000.0,16.51,0.0,0.0,34.0,8.0,0.0,11431.0,74.2,29.0,5449.27,5449.27,11431.20,11431.20,9550.73,1880.47,476.30,0.0,0.0,1514.0,272492.0,15400.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [191]:
data2.shape

(816676, 192)

In [192]:
data3 = data2.sample(frac=0.1, replace=False)

In [193]:
# pickled on 250502018
pd.to_pickle(data3,'dataupdate25052018 - 10percent.pkl')

In [48]:
# pickled on 230502018
#pd.to_pickle(data3,'dataupdate23052018 - 10percent.pkl')

In [21]:
# pickled on 22052018
#pd.to_pickle(data2,'dataupdate22052018 - full.pkl')
#pd.to_pickle(data3,'dataupdate22052018 - 10percent.pkl')

In [18]:
# pickled on 160502018
# pd.to_pickle(data2,'dataupdate16052018 - full.pkl')

In [102]:
#pd.to_pickle(data2,'dataupdate04052018 - full.pkl')

In [103]:
#data4 = data2.sample(frac=0.1, replace=False)

In [104]:
#pd.to_pickle(data4,'dataupdate04052018 - 10percent.pkl')

In [4]:
# data10 = pd.read_pickle('dataupdate02052018 - 1percent.pkl')
# data10 = data10.drop(['collection_recovery_fee', 'recoveries','total_rec_late_fee','next_pymnt_d_isthisrelevant?'], axis=1)
# pd.to_pickle(data10,'dataupdate07052018 - 1percent.pkl')